#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, with "Hi" on the 9th iteration
count=0
while [ $count -lt 10 ]
do
    echo "Best School"
    if [ $count -eq 8 ]
    then
        echo "Hi"
    fi
    ((count++))
done
