#!/usr/bin/env bash
# This script displays content of current directory, showing only part after first dash
for file in *
do
    if [[ "$file" != .* ]]
    then
        echo "$file" | cut -d'-' -f2-
    fi
done
