#!/usr/bin/env bash
# Init script that manages manage_my_process

PIDFILE="/var/run/my_process.pid"

case "$1" in
    start)
        ./manage_my_process &
        echo $! > $PIDFILE
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat $PIDFILE)" 2>/dev/null
        rm -f $PIDFILE
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(cat $PIDFILE)" 2>/dev/null
        rm -f $PIDFILE
        ./manage_my_process &
        echo $! > $PIDFILE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
EOF
